#include "App_AutoExitService_Internal.h"

static const AppAutoExitMotionStep g_profileStraight[] =
{
    { APP_AUTO_EXIT_DRIVE_FORWARD, APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_FORWARD_1_MS },
    { APP_AUTO_EXIT_DRIVE_STOP,    APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_FINAL_STOP_MS }
};

static const AppAutoExitMotionStep g_profileRight[] =
{
    { APP_AUTO_EXIT_DRIVE_FORWARD, APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_FORWARD_1_MS },
    { APP_AUTO_EXIT_DRIVE_FORWARD, APP_AUTO_EXIT_STEER_RIGHT,  APP_AUTO_EXIT_TURN_1_MS },
    { APP_AUTO_EXIT_DRIVE_STOP,    APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_SHIFT_STOP_MS },
    { APP_AUTO_EXIT_DRIVE_REVERSE, APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_REVERSE_1_MS },
    { APP_AUTO_EXIT_DRIVE_STOP,    APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_SHIFT_STOP_MS },
    { APP_AUTO_EXIT_DRIVE_FORWARD, APP_AUTO_EXIT_STEER_RIGHT,  APP_AUTO_EXIT_TURN_2_MS },
    { APP_AUTO_EXIT_DRIVE_STOP,    APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_SHIFT_STOP_MS },
    { APP_AUTO_EXIT_DRIVE_REVERSE, APP_AUTO_EXIT_STEER_LEFT,   APP_AUTO_EXIT_REVERSE_TURN_MS },
    { APP_AUTO_EXIT_DRIVE_STOP,    APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_SHIFT_STOP_MS },
    { APP_AUTO_EXIT_DRIVE_FORWARD, APP_AUTO_EXIT_STEER_RIGHT,  APP_AUTO_EXIT_TURN_3_MS },
    { APP_AUTO_EXIT_DRIVE_FORWARD, APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_FORWARD_2_MS },
    { APP_AUTO_EXIT_DRIVE_STOP,    APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_FINAL_STOP_MS }
};

static const AppAutoExitMotionStep g_profileLeft[] =
{
    { APP_AUTO_EXIT_DRIVE_FORWARD, APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_FORWARD_1_MS },
    { APP_AUTO_EXIT_DRIVE_FORWARD, APP_AUTO_EXIT_STEER_LEFT,   APP_AUTO_EXIT_TURN_1_MS },
    { APP_AUTO_EXIT_DRIVE_STOP,    APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_SHIFT_STOP_MS },
    { APP_AUTO_EXIT_DRIVE_REVERSE, APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_REVERSE_1_MS },
    { APP_AUTO_EXIT_DRIVE_STOP,    APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_SHIFT_STOP_MS },
    { APP_AUTO_EXIT_DRIVE_FORWARD, APP_AUTO_EXIT_STEER_LEFT,   APP_AUTO_EXIT_TURN_2_MS },
    { APP_AUTO_EXIT_DRIVE_STOP,    APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_SHIFT_STOP_MS },
    { APP_AUTO_EXIT_DRIVE_REVERSE, APP_AUTO_EXIT_STEER_RIGHT,  APP_AUTO_EXIT_REVERSE_TURN_MS },
    { APP_AUTO_EXIT_DRIVE_STOP,    APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_SHIFT_STOP_MS },
    { APP_AUTO_EXIT_DRIVE_FORWARD, APP_AUTO_EXIT_STEER_LEFT,   APP_AUTO_EXIT_TURN_3_MS },
    { APP_AUTO_EXIT_DRIVE_FORWARD, APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_FORWARD_2_MS },
    { APP_AUTO_EXIT_DRIVE_STOP,    APP_AUTO_EXIT_STEER_CENTER, APP_AUTO_EXIT_FINAL_STOP_MS }
};

const AppAutoExitMotionStep *AppAutoExitProfile_Get(AppAutoExitDirection direction,
                                                    uint32 *profileCount)
{
    const AppAutoExitMotionStep *profile;
    uint32 count;

    profile = 0;
    count = 0u;

    switch(direction)
    {
        case APP_AUTO_EXIT_DIR_STRAIGHT:
            profile = g_profileStraight;
            count = APP_AUTO_EXIT_ARRAY_COUNT(g_profileStraight);
            break;

        case APP_AUTO_EXIT_DIR_LEFT:
            profile = g_profileLeft;
            count = APP_AUTO_EXIT_ARRAY_COUNT(g_profileLeft);
            break;

        case APP_AUTO_EXIT_DIR_RIGHT:
            profile = g_profileRight;
            count = APP_AUTO_EXIT_ARRAY_COUNT(g_profileRight);
            break;

        default:
            break;
    }

    if(profileCount != 0)
    {
        *profileCount = count;
    }

    return profile;
}
